# Generated by Django 3.1.3 on 2020-11-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrer',
            name='email',
        ),
    ]
