# Generated by Django 3.1.3 on 2022-01-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_referrer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_address',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery_address',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
