# Generated by Django 3.1.3 on 2022-01-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220111_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
